# Generated by Django 2.0 on 2018-08-11 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CallSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.IntegerField(max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CallType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_workorder', models.CharField(max_length=20)),
                ('workorder_description', models.CharField(max_length=500)),
                ('report_datetime', models.DateTimeField(auto_now=True)),
                ('reported_by', models.CharField(max_length=200)),
                ('requesting_contact', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('local_time', models.CharField(max_length=50)),
                ('call_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.CallSubType')),
                ('call_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.CallType')),
                ('caller_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.CallerType')),
            ],
        ),
        migrations.CreateModel(
            name='RequestProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=2000)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Request')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_ip', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=10)),
                ('current_weather', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='service_locationid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ServiceLocation'),
        ),
        migrations.AddField(
            model_name='request',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Store'),
        ),
        migrations.AddField(
            model_name='callsubtype',
            name='call_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.CallType'),
        ),
    ]
